// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCErxrQLWj6xl38PKDa4C4RvIlfUEt0Akg',
    appId: '1:37737824184:web:076a1344eb241fea84d94d',
    messagingSenderId: '37737824184',
    projectId: 'cari-dekormu-f21d6',
    authDomain: 'cari-dekormu-f21d6.firebaseapp.com',
    storageBucket: 'cari-dekormu-f21d6.firebasestorage.app',
    measurementId: 'G-HJJ5WCD53W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbe6OfdQgY0g9gExilFA-BQrzd-uH7_9c',
    appId: '1:37737824184:android:bbb04c5e822fc33d84d94d',
    messagingSenderId: '37737824184',
    projectId: 'cari-dekormu-f21d6',
    storageBucket: 'cari-dekormu-f21d6.firebasestorage.app',
  );
}
